---
services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile
    command: |
      sh -c '
        set -euo pipefail
        # Use $$ to prevent interpolation 
        if [ $$(id -u) -ne 1000 ]; then
          exit 1
        fi
        crc32 --version # perl-archive-zip
        curl --version # curl
        git --version # git
        openssl --version # openssl
        pip --version # py3-pip
        python --version # python3
        rhash --version # rhash
        sha256sum --version # coreutils
        shasum --version # perl-utils
        xxhsum --version # xxhash
      '
